// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQCNrgHzeShMuLuT1CV7CAIrPvidfJ3vo',
    appId: '1:860784918200:web:9df9a6b485b41a6bf7be4d',
    messagingSenderId: '860784918200',
    projectId: 'my-flutter-project-4ccd3',
    authDomain: 'my-flutter-project-4ccd3.firebaseapp.com',
    storageBucket: 'my-flutter-project-4ccd3.appspot.com',
    measurementId: 'G-WR3SKB843R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDl6apk3MoW5MobeJldZA5VonzcBXfHzQk',
    appId: '1:860784918200:android:5ac186adc6324b79f7be4d',
    messagingSenderId: '860784918200',
    projectId: 'my-flutter-project-4ccd3',
    storageBucket: 'my-flutter-project-4ccd3.appspot.com',
  );
}
